server:
  port: 8082


spring:
  application:
    name: sq-user-server
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sq-user}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
#      username: ${REDIS_USER}
      password: ${REDIS_PASS} # 비밀번호만 사용
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sq-user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
