server:
  port: 8081


spring:
  application:
    name: sq-user
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sq-user}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
